apply styler, upd workflow for coverage

diff --git a/.github/workflows/rcheck.yml b/.github/workflows/rcheck.yml
--- a/.github/workflows/rcheck.yml
+++ b/.github/workflows/rcheck.yml
@@ -123,10 +123,33 @@ jobs:
       - name: Install covr
         if: runner.os == 'macOS'
         run: |
-          remotes::install_cran("covr")
+          cov <- covr::package_coverage(
+            quiet = FALSE,
+            clean = FALSE,
+            install_path = file.path(normalizePath(Sys.getenv("RUNNER_TEMP"), winslash = "/"), "package")
+          )
+          covr::to_cobertura(cov)
         shell: Rscript {0}
+  
+      - uses: codecov/codecov-action@v4
+        with:
+          # Fail if error if not on PR, or if on PR and token is given
+          fail_ci_if_error: ${{ github.event_name != 'pull_request' || secrets.CODECOV_TOKEN }}
+          file: ./cobertura.xml
+          plugin: noop
+          disable_search: true
+          token: ${{ secrets.CODECOV_TOKEN }}
 
-      - name: Test coverage
-        if: runner.os == 'macOS'
-        run: covr::codecov()
-        shell: Rscript {0}
+      - name: Show testthat output
+        if: always()
+        run: |
+          ## --------------------------------------------------------------------
+          find '${{ runner.temp }}/package' -name 'testthat.Rout*' -exec cat '{}' \; || true
+        shell: bash
+
+      - name: Upload test results
+        if: failure()
+        uses: actions/upload-artifact@v4
+        with:
+          name: coverage-test-failures
+          path: ${{ runner.temp }}/package
